services:
  transmetro-front:
    build:
      context: .
    image: transmetro-front:latest
    container_name: transmetro_frontend
    restart: unless-stopped
    ports:
      - "${FRONT_PORT}:80"
    environment:
      API_PROXY_URL: ${API_PROXY_URL}
    networks:
      - mysql_net

networks:
  mysql_net:
    external: true